### ISSUE TITLE
insserv rejected the script header

### ISSUE THREAD

**Issue by dimmingmuse** [vortex-5/utorrent_initd#2]
I get the following when I try "update-rc.d utorrent defaults": 

insserv: warning: script 'utorrent' missing LSB tags and overrides
insserv: There is a loop between service monit and utorrent if stopped
insserv:  loop involving service utorrent at depth 2
insserv:  loop involving service monit at depth 1
insserv: Stopping utorrent depends on monit and therefore on system facility `$all' which can not be true!
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header

I assume this is a problem with the script, but I don't know for sure.

**Comment by vortex-5** [comment]
I am no longer maintaining the initd script I do have a newer systemd script however I haven't yet put it up on github.

**Comment by vortex-5** [comment]
Oops I forgot it was already published here: https://github.com/vortex-5/utorrent-ubuntu-service

This script is written for systemd so that means ubuntu redhat etc. systemd is the new service runner standard going forward if you're unsure if your system has systemd check to see if you have the "systemctl" command
